# Generated by Django 2.1 on 2018-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0003_vote")]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        )
    ]
