# Generated by Django 2.1 on 2018-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_auto_20180822_1228")]

    operations = [
        migrations.AlterField(
            model_name="group", name="route", field=models.CharField(max_length=30)
        )
    ]
