# Generated by Django 2.1 on 2018-08-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0006_auto_20180822_1427")]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_enabled",
            field=models.BooleanField(default=True),
            preserve_default=False,
        )
    ]
