# Generated by Django 2.1 on 2018-08-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0007_place_is_enabled")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.Group"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membership",
            name="place",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.Place"
            ),
            preserve_default=False,
        ),
    ]
