# Generated by Django 2.1 on 2018-08-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_place_date_added")]

    operations = [
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.CharField(default="default", max_length=300),
            preserve_default=False,
        )
    ]
